# -*- mode: yaml -*-
# vim: set filetype=yaml tabstop=4 shiftwidth=4 autoindent smartindent:
site_name: "Is Bitcoin True?"
site_url: https://rschristopher.github.io/
site_description: "Is Bitcoin True?"
site_author: RS Christopher
docs_dir: src
site_dir: docs
copyright: Copyright &copy; 2022 R.S. Christopher
extra:
    generator: false
extra_css:
    - css/extra.css
theme:
    name: material
    features:
        - navigation.indexes
        - navigation.sections
        - navigation.tabs
        - navigation.top
    palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    logo: images/bitcoin-logo-bw.png
    favicon: images/favicon.png

nav:
    - Home: 
        - index.md
        - Is Bitcoin True?: is-bitcoin-true.md
        - Bitcoin as Money: 
          - bitcoin-as-money/index.md
          - Unit of Account: bitcoin-as-money/unit-of-account.md
          - Medium of Exchange: bitcoin-as-money/medium-of-exchange.md
          - Store of Value: bitcoin-as-money/store-of-value.md
          - Fixed Supply: bitcoin-as-money/fixed-supply.md
          - Monetary Policy: bitcoin-as-money/monetary-policy.md
          - Easy Money vs Hard Money: bitcoin-as-money/easy-vs-hard.md
          - Separation of Money and State: bitcoin-as-money/separation-money-and-state.md
        - Criticisms:
          - criticisms/index.md
          - Deflation: criticisms/deflation.md
          - Environment: criticisms/environment.md
          - Scalability: criticisms/scalability.md
          - Turing Incomplete: criticisms/turing-complete.md
          - Quantum Computing: criticisms/quantum-computing.md
          - Cantillon Bubbles: criticisms/cantillon.md
          - Whitelisting: criticisms/whitelisting.md
          - Why is it not Worth More?: criticisms/why-is-it-not-worth-more.md
    - Custody:
        - custody/index.md
        - Wallets and Keys and UTXOs: custody/wallets-and-keys.md
        - Creating Keys: 
          - custody/creating-keys/index.md
          - Using Dice: custody/creating-keys/dice.md
          - Dice and Paper: custody/creating-keys/dice-and-paper.md
          - Dice and Computer: custody/creating-keys/dice-and-computer.md
          - Multisig: custody/creating-keys/multisig.md
        - Using Keys:
          - custody/using-keys/index.md
          - Generating Addresses: custody/using-keys/generating-addresses.md
          - Signing Transactions: custody/using-keys/signing-transactions.md
        - Securing Keys:
          - custody/securing-keys/index.md
          - Airgapped Computer: custody/securing-keys/airgapped-computer.md
          - Bare Metal: custody/securing-keys/bare-metal.md
          - Hardware Wallets: custody/securing-keys/hardware-wallets.md
          - Mnemonic Memorization: custody/securing-keys/memorization.md
        - Protocols:
          - custody/protocols/index.md
          - Glacier Overview: custody/protocols/glacier.md
          - Basic: custody/protocols/basic.md
          - Ridiculous: custody/protocols/ridiculous.md
          - Ludicrous: custody/protocols/ludicrous.md
          - Custom: custody/protocols/custom.md
        - Advanced:
          - Blockchain Analytics: custody/advanced/blockchain-analytics.md
          - Keyless Vault and Covenant: custody/advanced/keyless-vaults.md
    - Execution:
        - execution/index.md
        - Exchanges: 
          - execution/exchanges/index.md
          - Peer-to-Peer: execution/exchanges/peer-to-peer.md
        - Payments:
          - execution/payments/index.md
          - Base Layer (on-chain): execution/payments/base-layer.md
          - Layer 2 (lightning): execution/payments/lightning.md
        - Privacy: 
          - execution/privacy/index.md
          - AML/KYC: execution/privacy/kyc.md
          - Coinjoin: execution/privacy/coinjoin.md
          - Lightning: execution/privacy/lightning.md
        - Run a Node: 
          - execution/run-a-node/index.md
          - Bitcoin Full Node: execution/run-a-node/bitcoin-full.md
          - Lightning Node: execution/run-a-node/lightning.md
        - Localism: 
          - execution/localism/index.md
          - Local Area Networks: execution/localism/lan.md
          - Local Lightning: execution/localism/lightning.md
        - Advanced: 
          - Bitcoin Script: execution/advanced/bitcoin-script.md
          - Network Security: execution/advanced/network-security.md
          - Physical Security: execution/advanced/physical-security.md
    - Finance:
        - finance/index.md
        - Modern Investing: finance/modern-investing.md
        - Bitcoin-backed Loans: finance/bitcoin-backed-loans.md
        - Derivatives and Options: finance/derivatives.md
    - Mining:
        - mining/index.md
        - How it Works: mining/how-it-works.md
        - Home Mining: mining/home-mining.md
        - PoW and Energy Money: mining/pow-energy-money.md
    - References: references/index.md

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - toc:
      permalink: True
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

