# -*- mode: yaml -*-
# vim: set filetype=yaml tabstop=4 shiftwidth=4 autoindent smartindent:
site_name: "Is Bitcoin True?"
site_url: https://rschristopher.github.io/
site_description: "Is Bitcoin True?"
site_author: RS Christopher
docs_dir: src
site_dir: docs
extra_css:
    - css/extra.css
theme:
    name: material
    features:
        - navigation.indexes
        - navigation.sections
        - navigation.tabs
        - navigation.top
    palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    custom_dir: overrides
    logo: images/bitcoin-logo-bw.png
    favicon: images/favicon.png

nav:
    - Home: 'is-bitcoin-true/index.md'
    - Bitcoin is Money:
        - What is Money: 
          - what-is-bitcoin/index.md
          - Unit of Account: what-is-bitcoin/unit-of-account.md
          - Medium of Exchange: what-is-bitcoin/medium-of-exchange.md
          - Store of Value: what-is-bitcoin/store-of-value.md
        - Bitcoin's Monetary Policy: 'is-bitcoin-true/is-sound-money-important.md'
        - Easy Money vs Hard Money: 'is-bitcoin-true/is-fixed-supply-important.md'
        - Fixed Supply: 'is-bitcoin-true/is-fixed-supply-feasible.md'
        - Separation of Money and State: 'is-bitcoin-true/is-it-possible-to-separate-money-and-state.md'
        - Criticisms:
          - criticisms/index.md
          - Environment: criticisms/index.md
          - Scalability: criticisms/index.md
          - Turing Completion and Shitcoin Casinos: criticisms/index.md
          - Quantum Computing and Bounty of all Bounties: criticisms/index.md
          - Cantillon Bubbles: criticisms/index.md
          - Whitelisting and the Surveilance State: criticisms/index.md
          - Why is not Worth More?: 'is-bitcoin-true/why-is-it-not-worth-more.md'
    - Custody:
        - Wallets, Cold and Hot: custody/self-custody.md
        - Creating Keys: 
          - custody/creating-keys/index.md
          - Command Line: custody/self-custody.md
          - Dice-rolled: custody/self-custody.md
          - Multisig: custody/self-custody.md
        - Using Keys: 
          - Generating Addresses: custody/self-custody.md
          - Signing Transactions: custody/self-custody.md
          - Understanding UTXOs: custody/self-custody.md
        - Securing Keys: 
          - Bare Metal: custody/self-custody.md
          - Hardware Wallets: custody/self-custody.md
          - Mnemonic Memorization: custody/self-custody.md
        - Protocols: 
          - Glacier Protocol: custody/self-custody.md
          - Proof-of-Control: custody/self-custody.md
          - Custom Self-Custody Protocol: custody/self-custody.md
        - Advanced:
          - Blockchain Analytics: custody/self-custody.md
          - Keyless Vault and Covenant: custody/self-custody.md
    - Execution:
        - execution/index.md
        - Exchanges: 
          - execution/exchanges.md
          - P2P: execution/index.md
        - Payments:
          - payments/index.md
          - Base Layer (on-chain): payments/index.md
          - Second Layer (lightning): payments/index.md
        - Localism: payments/index.md
        - Privacy: 
          - payments/index.md
          - AML/KYC: execution/index.md
        - Run a Node: execution/index.md
        - Advanced: execution/index.md
    - Financing:
        - financing/index.md
        - Modern Investing: financing/index.md
        - Bitcoin-backed Loans: financing/index.md
        - Derivatives and Options: financing/index.md
    - Mining:
        - mining/index.md
        - How it Works: mining/index.md
        - Home Mining: mining/index.md
        - PoW and Energy Money: mining/index.md
    - References: references/index.md

markdown_extensions:
  - admonition
  - toc:
      permalink: True


