# -*- mode: yaml -*-
# vim: set filetype=yaml tabstop=4 shiftwidth=4 autoindent smartindent:
site_name: "Is Bitcoin True?"
site_url: https://rschristopher.github.io/
site_description: "Is Bitcoin True?"
site_author: RS Christopher
docs_dir: src
site_dir: docs
copyright: Copyright &copy; 2022 R.S. Christopher
extra:
    generator: false
extra_css:
    - css/extra.css
theme:
    name: material
    features:
        - navigation.indexes
        - navigation.sections
        - navigation.tabs
        - navigation.top
    palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    logo: images/bitcoin-logo-bw.png
    favicon: images/favicon.png

nav:
    - Bitcoin: 
        - index.md
        - Bitcoin as Money: 
          - bitcoin-as-money/index.md
          - Unit of Account: bitcoin-as-money/unit-of-account.md
          - Medium of Exchange: bitcoin-as-money/medium-of-exchange.md
          - Store of Value: bitcoin-as-money/store-of-value.md
          - Fixed Supply: bitcoin-as-money/fixed-supply.md
          - Monetary Policy: bitcoin-as-money/monetary-policy.md
          - Money and State: bitcoin-as-money/money-and-state.md
        - Criticisms:
          - criticisms/index.md
          - Cantillon Bubbles: criticisms/cantillon.md
          - Deflation: criticisms/deflation.md
          - Environment: criticisms/environment.md
          - Inequality: criticisms/inequality.md
          - Mining is Zero-sum: criticisms/mining-zero-sum.md
          - Quantum Computing: criticisms/quantum-computing.md
          - Scalability: criticisms/scalability.md
          - Surveillance: criticisms/surveillance.md
          - Why is it not Worth More?: criticisms/why-is-it-not-worth-more.md
        - Is Bitcoin True?: is-bitcoin-true.md
    - Saving:
        - saving/index.md
        - Understand the Terms: saving/understand-the-terms.md
        - Self Custody:
            - saving/self-custody/index.md
            - "Level 1: Getting Started": saving/self-custody/level-1.md
            - "Level 2: Your Keys": saving/self-custody/level-2.md
            - "Level 3: Dedicated Hardware": saving/self-custody/level-3.md
            - "Level 4: Full Node": saving/self-custody/level-4.md
            - "Level 5: Airgap Quarantine": saving/self-custody/level-5.md
            - "Level 6: Metal Backup": saving/self-custody/level-6.md
        - Wealth Preservation: 
            - saving/wealth/index.md
            - Full Privacy: saving/wealth/full-privacy.md
            - Inheritance Planning: saving/wealth/inheritance.md
            - Physical Security: saving/wealth/physical-security.md
        - Self Sovereignty:
            - saving/self-sovereignty/index.md
            - "Level 7: Protocols + Multisig": saving/self-sovereignty/level-7.md
            - "Level 8: DMZs": saving/self-sovereignty/level-8.md
            - "Level 9: Fault Tolerance": saving/self-sovereignty/level-9.md
            - "Level 10: Fail-safes": saving/self-sovereignty/level-10.md
            - "Level 11: Countermeasures": saving/self-sovereignty/level-11.md
            - "Level 12: Off-grid Operations": saving/self-sovereignty/level-12.md
        - Appendix:
            - "A: Airgapped Computer": saving/appendix/airgapped-computer.md
            - "A: Using Dice": saving/appendix/dice.md
            - "A: Custom Protocols": saving/appendix/custom.md
            - "A: Keyless Vaults": saving/appendix/keyless-vaults.md
            - "A: Mnemonic Memorization": saving/appendix/mnemonic.md
    - Commerce:
        - commerce/index.md
        - Payments:
          - commerce/payments/index.md
          - Base Layer (on-chain): commerce/payments/base-layer.md
          - Layer 2 (lightning): commerce/payments/lightning.md
        - Privacy: 
          - commerce/privacy/index.md
          - AML/KYC: commerce/privacy/kyc.md
          - Coinjoin: commerce/privacy/coinjoin.md
          - Lightning: commerce/privacy/lightning.md
        - Run a Node: 
          - commerce/run-a-node/index.md
          - Bitcoin Full Node: commerce/run-a-node/bitcoin-full.md
          - Lightning Node: commerce/run-a-node/lightning.md
        - Localism: 
          - commerce/localism/index.md
          - Local Area Networks: commerce/localism/lan.md
          - Local Lightning: commerce/localism/lightning.md
        - Advanced: 
          - Bitcoin Script: commerce/advanced/bitcoin-script.md
          - Network Security: commerce/advanced/network-security.md
          - Physical Security: commerce/advanced/physical-security.md
    - Proof of Work:
        - pow/index.md
        - How it Works: pow/how-it-works.md
        - Home Mining: pow/home-mining.md
        - PoW and Energy Money: pow/pow-energy-money.md
    - References: references/index.md

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - toc:
      permalink: True
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

