# -*- mode: yaml -*-
# vim: set filetype=yaml tabstop=4 shiftwidth=4 autoindent smartindent:
site_name: "Is Bitcoin True?"
site_url: https://rschristopher.github.io/
site_description: "Is Bitcoin True?"
site_author: RS Christopher

repo_url: https://github.com/rschristopher/rschristopher.github.io
repo_name: rschristopher/rschristopher.github.io
edit_uri: ""
docs_dir: src
site_dir: docs

theme:
    name: material
    features:
        - navigation.indexes
    palette:
        primary: black
    custom_dir: mkdocs-overrides
    logo: images/logo.png
    favicon: images/favicon.png

nav:
    - What is Bitcoin?:
        - what-is-bitcoin/index.md
        - Store of Value: what-is-bitcoin/store-of-value.md
    - Custody:
        - custody/index.md
        - Self Custody: custody/self-custody.md

markdown_extensions:
  - admonition
  - toc:
      permalink: True
