# -*- mode: yaml -*-
# vim: set filetype=yaml tabstop=4 shiftwidth=4 autoindent smartindent:
site_name: "Is Bitcoin True?"
site_url: https://rschristopher.github.io/
site_description: "Is Bitcoin True?"
site_author: RS Christopher
docs_dir: src
site_dir: docs

theme:
    name: material
    features:
        - navigation.indexes
    palette:
    - scheme: default
      primary: black
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
    custom_dir: mkdocs-overrides
    logo: images/logo.png
    favicon: images/favicon.png

nav:
    - What is Bitcoin?:
        - what-is-bitcoin/index.md
        - Store of Value: what-is-bitcoin/store-of-value.md
    - Custody:
        - custody/index.md
        - Self Custody: custody/self-custody.md

markdown_extensions:
  - admonition
  - toc:
      permalink: True
