# -*- mode: yaml -*-
# vim: set filetype=yaml tabstop=4 shiftwidth=4 autoindent smartindent:
site_name: "Is Bitcoin True?"
site_url: https://rschristopher.github.io/
site_description: "Is Bitcoin True?"
site_author: RS Christopher
docs_dir: src
site_dir: docs
copyright: Copyright &copy; 2022 R.S. Christopher
extra:
    generator: false
extra_css:
    - css/extra.css
theme:
    name: material
    features:
        - navigation.indexes
        - navigation.sections
        - navigation.tabs
        - navigation.top
    palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    logo: images/bitcoin-logo-bw.png
    favicon: images/favicon.png

nav:
    - Bitcoin: 
        - index.md
        - Is Bitcoin True?: is-bitcoin-true.md
        - Bitcoin as Money: 
          - bitcoin-as-money/index.md
          - Unit of Account: bitcoin-as-money/unit-of-account.md
          - Medium of Exchange: bitcoin-as-money/medium-of-exchange.md
          - Store of Value: bitcoin-as-money/store-of-value.md
          - Fixed Supply: bitcoin-as-money/fixed-supply.md
          - Monetary Policy: bitcoin-as-money/monetary-policy.md
          - Separation of Money and State: bitcoin-as-money/separation-money-and-state.md
        - Criticisms:
          - criticisms/index.md
          - Cantillon Bubbles: criticisms/cantillon.md
          - Deflation: criticisms/deflation.md
          - Environment: criticisms/environment.md
          - Inequality: criticisms/inequality.md
          - Quantum Computing: criticisms/quantum-computing.md
          - Scalability: criticisms/scalability.md
          - Surveillance: criticisms/surveillance.md
          - Turing Incomplete: criticisms/turing-complete.md
          - Why is it not Worth More?: criticisms/why-is-it-not-worth-more.md
    - Saving:
        - saving/index.md
        - Imperfect Metaphors: saving/imperfect-metaphors.md
        - Airgapped Computer: saving/airgapped-computer.md
        - Hardware Wallets: saving/hardware-wallets.md
        - Creating Keys: 
          - saving/creating-keys/index.md
          - Using Dice: saving/creating-keys/dice.md
          - Dice and Paper: saving/creating-keys/dice-and-paper.md
          - Dice and Computer: saving/creating-keys/dice-and-computer.md
          - Multisig: saving/creating-keys/multisig.md
        - Using Keys:
          - saving/using-keys/index.md
          - Generating Addresses: saving/using-keys/generating-addresses.md
          - Signing Transactions: saving/using-keys/signing-transactions.md
        - Securing Keys:
          - saving/securing-keys/index.md
          - Bare Metal: saving/securing-keys/bare-metal.md
          - Mnemonic Memorization: saving/securing-keys/memorization.md
        - Protocols:
          - saving/protocols/index.md
          - Basic+: saving/protocols/basic.md
          - Ridiculous: saving/protocols/ridiculous.md
          - Ludicrous: saving/protocols/ludicrous.md
          - Custom: saving/protocols/custom.md
        - Advanced:
          - Blockchain Analytics: saving/advanced/blockchain-analytics.md
          - Keyless Vault and Covenant: saving/advanced/keyless-vaults.md
    - Commerce:
        - commerce/index.md
        - Exchanges: 
          - commerce/exchanges/index.md
          - Peer-to-Peer: commerce/exchanges/peer-to-peer.md
        - Payments:
          - commerce/payments/index.md
          - Base Layer (on-chain): commerce/payments/base-layer.md
          - Layer 2 (lightning): commerce/payments/lightning.md
        - Privacy: 
          - commerce/privacy/index.md
          - AML/KYC: commerce/privacy/kyc.md
          - Coinjoin: commerce/privacy/coinjoin.md
          - Lightning: commerce/privacy/lightning.md
        - Run a Node: 
          - commerce/run-a-node/index.md
          - Bitcoin Full Node: commerce/run-a-node/bitcoin-full.md
          - Lightning Node: commerce/run-a-node/lightning.md
        - Localism: 
          - commerce/localism/index.md
          - Local Area Networks: commerce/localism/lan.md
          - Local Lightning: commerce/localism/lightning.md
        - Advanced: 
          - Bitcoin Script: commerce/advanced/bitcoin-script.md
          - Network Security: commerce/advanced/network-security.md
          - Physical Security: commerce/advanced/physical-security.md
    - Issuance:
        - issuance/index.md
        - How it Works: issuance/how-it-works.md
        - Home Mining: issuance/home-mining.md
        - PoW and Energy Money: issuance/pow-energy-money.md
    - References: references/index.md

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - toc:
      permalink: True
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

