[tool.poetry]
name = "rschristopher.github.io"
version = "0.1.0"
description = ""
authors = ["RS Christopher <rschristopher@avant.net>"]

[tool.poetry.dependencies]
python = "^3.8"
mkdocs = "^1.3.0"
mkdocs-material = "^8.2.13"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
